# Generated by Django 4.0 on 2023-05-12 13:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('filter_published', django.db.models.manager.Manager()),
            ],
        ),
    ]
