---
name: Checks

on: [push, pull_request_review]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pip and packages
        uses: luisgs7/pip-packages@v1

      - name: Test Recipe App
        run: pytest -m "not functional_test"

      - name: Lint Flake8
        run: flake8 project/* recipes/* utils/*

      - name: Generate Report
        run: coverage run -m pytest -m "not functional_test"

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
